remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins

title: [Mizeto]
description: [Welcome To My Github page ]

show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

